appId: com.saucelabs.mydemo.app.ios
name: My Demo App (iOS)

tags:
  - login
  - positive
  - negative
  - edge
  - catalog
  - cart
  - checkout
  - crud-read
  - crud-create
  - crud-update
  - crud-delete
