appId: com.saucelabs.mydemo.app.ios
name: My Demo App iOS - Maestro

flows:
  - "flows/login/*"
  - "flows/catalog/*"
  - "flows/checkout/*"

testOutputDir: build/maestro-results

platform:
  ios:
    snapshotKeyHonorModalViews: true
